### PR TITLE
COMMERCE-7083 test

### PR DESCRIPTION
**Pull request by epark18**

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:Product Info Management

**Comment by epark18** [comment]
ci:test:commerce:functional

**Comment by epark18** [comment]
ci:stop

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by epark18** [comment]
ci:stop

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by epark18** [comment]
ci:test:commerce-functional

**Comment by bronsonsoda** [comment]
Looks good 👍

**Pull request closed without merging**
